// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKP6_8Ozzeq4tVFrosUHvjcuS4bhCHJZU',
    appId: '1:1061388735213:web:e75026d010f726e7c432e4',
    messagingSenderId: '1061388735213',
    projectId: 'mediq-60b44',
    authDomain: 'mediq-60b44.firebaseapp.com',
    storageBucket: 'mediq-60b44.firebasestorage.app',
    measurementId: 'G-J8FRNHM35T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqXGCzhWoBgiDdOOp0bR-rgkMFqg3nijs',
    appId: '1:1061388735213:android:07a1fcbf4b447657c432e4',
    messagingSenderId: '1061388735213',
    projectId: 'mediq-60b44',
    storageBucket: 'mediq-60b44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH6yuZZ1JdHz9d2E2gG1j3M6yVl0BZPts',
    appId: '1:1061388735213:ios:360390d2a101c109c432e4',
    messagingSenderId: '1061388735213',
    projectId: 'mediq-60b44',
    storageBucket: 'mediq-60b44.firebasestorage.app',
    iosBundleId: 'com.example.mediq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH6yuZZ1JdHz9d2E2gG1j3M6yVl0BZPts',
    appId: '1:1061388735213:ios:360390d2a101c109c432e4',
    messagingSenderId: '1061388735213',
    projectId: 'mediq-60b44',
    storageBucket: 'mediq-60b44.firebasestorage.app',
    iosBundleId: 'com.example.mediq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKP6_8Ozzeq4tVFrosUHvjcuS4bhCHJZU',
    appId: '1:1061388735213:web:a289834e7975a8c2c432e4',
    messagingSenderId: '1061388735213',
    projectId: 'mediq-60b44',
    authDomain: 'mediq-60b44.firebaseapp.com',
    storageBucket: 'mediq-60b44.firebasestorage.app',
    measurementId: 'G-36K33PJD4W',
  );
}
